import pandas as pd
import plotly.graph_objects as go

# Read data from 'waste_gen_eu.tsv'
df = pd.read_csv("data/waste_gen_eu.tsv", sep="\t")

# Only use the first 1000 rows
# df = df.head(2500)

# Replace ':' with '0'
df = df.replace(': ', '0')

# Replace ': c' with '0'
df = df.replace(': c', '0')

# Remove letters from columns B-J and rows 2 onwards
df.iloc[1:, 1:10] = df.iloc[1:, 1:10].replace('[a-zA-Z]', '', regex=True)

# Replace ':' with '0'
df = df.replace(': ', '0')

# Rename 'freq,unit,hazard,nace_r2,waste,geo\TIME_PERIOD' to 'category/country'
df = df.rename(columns={'freq,unit,hazard,nace_r2,waste,geo\TIME_PERIOD':'category/country'})

# Each element in 'category/country' looks like 'A,T,HAZ_NHAZ,A,PRIM,AT'. Let's remove 'A,T,HAZ_NHAZ'
df['category/country'] = df['category/country'].str[13:]

# Create a new column called 'country' and set it to the last element in 'category/country'
df['country'] = df['category/country'].str.split(",").str[-1]

# Create a new column called 'category' and set it to the first element in 'category/country'
df['category'] = df['category/country'].str.split(",").str[0]

# Create a new column called 'waste' and set it to the second element in 'category/country'
df['waste'] = df['category/country'].str.split(",").str[1]

# Remove 'E', 'E38', 'G4677', 'TOTAL_HH' from 'category'
df = df[df['category'].isin(['E', 'E38', 'G4677', 'TOTAL_HH']) == False]

# Delete the 'category/country' column
df = df.drop(columns=['category/country'])

# Move the 'waste' column to the front
df = df[['waste'] + [col for col in df.columns if col != 'waste']]

# Move the 'category' column to the front
df = df[['category'] + [col for col in df.columns if col != 'category']]

# Move the 'country' column to the front
df = df[['country'] + [col for col in df.columns if col != 'country']]

# Filter for 'C20-C22'
df = df[df['category'] == 'C20-C22']

# Filter for W074
df = df[df['waste'] == 'W074']

# Remove extra spaces from the column names
df.columns = df.columns.str.strip()

# Create a dictionary that maps country codes to country names
country_names = {
    'AT': 'Austria',
    'BA': 'Bosnia and Herzegovina',
    'BE': 'Belgium',
    'BG': 'Bulgaria',
    'CY': 'Cyprus',
    'CZ': 'Czech Republic',
    'DE': 'Germany',
    'DK': 'Denmark',
    'EE': 'Estonia',
    'EL': 'Greece',
    'ES': 'Spain',
    'FI': 'Finland',
    'FR': 'France',
    'HR': 'Croatia',
    'HU': 'Hungary',
    'IE': 'Ireland',
    'IS': 'Iceland',
    'IT': 'Italy',
    'LI': 'Liechtenstein',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'LV': 'Latvia',
    'ME': 'Montenegro',
    'MK': 'North Macedonia',
    'MT': 'Malta',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'PL': 'Poland',
    'PT': 'Portugal',
    'RO': 'Romania',
    'RS': 'Serbia',
    'SE': 'Sweden',
    'SI': 'Slovenia',
    'SK': 'Slovakia',
    'TR': 'Turkey',
    'UK': 'United Kingdom',
    'XK': 'Kosovo'
}

# Replace the country codes in the 'country' column with their respective names
df['country'] = df['country'].replace(country_names)

# Filter for the countries we want to keep, United Kingdom, Spain, France, Italy, Germany
df = df[df['country'].isin(['United Kingdom', 'Spain', 'France', 'Italy', 'Germany'])]

# Convert the values in the year columns to numeric
df[df.columns[3:]] = df[df.columns[3:]].apply(pd.to_numeric)

# Create a plotly figure
fig = go.Figure()

# Loop through each country in the dataframe, if the value is 0 then set it to None
for country in df['country'].unique():
    # Filter the dataframe for the current country
    df_country = df[df['country'] == country]
    # Add a line trace for the current country
    fig.add_trace(
        go.Scatter(x=df.columns[3:], y=df_country.iloc[0, 3:].replace(0, None), name=country)
    )

# Set the x-axis title
fig.update_xaxes(title_text='Year')

# Set the y-axis title
fig.update_yaxes(title_text='Waste Generated (tonnes)')

# Improve readability of the hover labels, no decimals
fig.update_traces(hovertemplate='%{y:.0f}')

fig.update_layout(title_text='Waste Generated by Country in Europe')

# White background, grey gridlines
fig.update_layout(
    hovermode='x unified',
    plot_bgcolor='white',
    title_x=0.5,
    title_y=0.88,
    xaxis=dict(
        gridcolor='LightGrey'
    ),
    yaxis=dict(
        gridcolor='LightGrey'
    )
)

# Better images
config = {
  'toImageButtonOptions': {
    'format': 'png', # one of png, svg, jpeg, webp
    'filename': 'custom_image',
    'height': 575,
    'width': 796,
    'scale':10 # Multiply title/legend/axis/canvas sizes by this factor
  }
}

# Show the figure
fig.show(config=config)